// Code generated by sqlc. DO NOT EDIT.
package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgxpool"
)

type DBTX interface {
	Exec(context.Context, string, ...interface{}) (interface{}, error)
	Query(context.Context, string, ...interface{}) (interface{}, error)
	QueryRow(context.Context, string, ...interface{}) interface{}
}

func New(db *pgxpool.Pool) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db *pgxpool.Pool
}
