// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package store

import (
	"context"
)

const createItemDocument = `-- name: CreateItemDocument :one
INSERT INTO item_documents (item_id, filename, content_type, file_path, size)
VALUES ($1, $2, $3, 'pending', 0)
RETURNING id, item_id, filename, content_type, file_path, size, created_at
`

type CreateItemDocumentParams struct {
	ItemID      string `json:"item_id"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
}

func (q *Queries) CreateItemDocument(ctx context.Context, arg CreateItemDocumentParams) (ItemDocument, error) {
	row := q.db.QueryRow(ctx, createItemDocument, arg.ItemID, arg.Filename, arg.ContentType)
	var i ItemDocument
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Filename,
		&i.ContentType,
		&i.FilePath,
		&i.Size,
		&i.CreatedAt,
	)
	return i, err
}

const deleteItemDocument = `-- name: DeleteItemDocument :exec
DELETE FROM item_documents WHERE id = $1
`

func (q *Queries) DeleteItemDocument(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteItemDocument, id)
	return err
}

const getItemDocumentFilePath = `-- name: GetItemDocumentFilePath :one
SELECT file_path FROM item_documents WHERE id = $1 AND item_id = $2
`

type GetItemDocumentFilePathParams struct {
	ID     string `json:"id"`
	ItemID string `json:"item_id"`
}

func (q *Queries) GetItemDocumentFilePath(ctx context.Context, arg GetItemDocumentFilePathParams) (string, error) {
	row := q.db.QueryRow(ctx, getItemDocumentFilePath, arg.ID, arg.ItemID)
	var file_path string
	err := row.Scan(&file_path)
	return file_path, err
}

const listItemDocuments = `-- name: ListItemDocuments :many
SELECT id, item_id, filename, content_type, file_path, size, created_at
FROM item_documents WHERE item_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListItemDocuments(ctx context.Context, itemID string) ([]ItemDocument, error) {
	rows, err := q.db.Query(ctx, listItemDocuments, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemDocument
	for rows.Next() {
		var i ItemDocument
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Filename,
			&i.ContentType,
			&i.FilePath,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemDocumentPath = `-- name: UpdateItemDocumentPath :exec
UPDATE item_documents SET file_path = $1, size = $2 WHERE id = $3
`

type UpdateItemDocumentPathParams struct {
	FilePath string `json:"file_path"`
	Size     int64  `json:"size"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateItemDocumentPath(ctx context.Context, arg UpdateItemDocumentPathParams) error {
	_, err := q.db.Exec(ctx, updateItemDocumentPath, arg.FilePath, arg.Size, arg.ID)
	return err
}
