// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: electrical_breakers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBreakerAtSlot = `-- name: CountBreakerAtSlot :one
SELECT COUNT(*) FROM electrical_breakers WHERE panel_id = $1 AND slot = $2
`

type CountBreakerAtSlotParams struct {
	PanelID string `json:"panel_id"`
	Slot    int32  `json:"slot"`
}

func (q *Queries) CountBreakerAtSlot(ctx context.Context, arg CountBreakerAtSlotParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBreakerAtSlot, arg.PanelID, arg.Slot)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBreakersAtDoublePoleSlots = `-- name: CountBreakersAtDoublePoleSlots :one
SELECT COUNT(*) FROM electrical_breakers WHERE panel_id = $1 AND (slot = $2 OR slot = $3)
`

type CountBreakersAtDoublePoleSlotsParams struct {
	PanelID string `json:"panel_id"`
	Slot    int32  `json:"slot"`
	Slot_2  int32  `json:"slot_2"`
}

func (q *Queries) CountBreakersAtDoublePoleSlots(ctx context.Context, arg CountBreakersAtDoublePoleSlotsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBreakersAtDoublePoleSlots, arg.PanelID, arg.Slot, arg.Slot_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBreaker = `-- name: CreateBreaker :one
INSERT INTO electrical_breakers (panel_id, slot, label, amps, breaker_type, is_gfci, is_afci, notes, floor_plan_area_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, panel_id, slot, label, amps, breaker_type, is_gfci, is_afci, notes, floor_plan_area_id, created_at, updated_at
`

type CreateBreakerParams struct {
	PanelID         string      `json:"panel_id"`
	Slot            int32       `json:"slot"`
	Label           *string     `json:"label"`
	Amps            pgtype.Int4 `json:"amps"`
	BreakerType     string      `json:"breaker_type"`
	IsGfci          bool        `json:"is_gfci"`
	IsAfci          bool        `json:"is_afci"`
	Notes           *string     `json:"notes"`
	FloorPlanAreaID *string     `json:"floor_plan_area_id"`
}

func (q *Queries) CreateBreaker(ctx context.Context, arg CreateBreakerParams) (ElectricalBreaker, error) {
	row := q.db.QueryRow(ctx, createBreaker,
		arg.PanelID,
		arg.Slot,
		arg.Label,
		arg.Amps,
		arg.BreakerType,
		arg.IsGfci,
		arg.IsAfci,
		arg.Notes,
		arg.FloorPlanAreaID,
	)
	var i ElectricalBreaker
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.Slot,
		&i.Label,
		&i.Amps,
		&i.BreakerType,
		&i.IsGfci,
		&i.IsAfci,
		&i.Notes,
		&i.FloorPlanAreaID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBreaker = `-- name: DeleteBreaker :exec
DELETE FROM electrical_breakers WHERE id = $1
`

func (q *Queries) DeleteBreaker(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBreaker, id)
	return err
}

const getBreaker = `-- name: GetBreaker :one
SELECT id, panel_id, slot, label, amps,
       breaker_type, is_gfci, is_afci, notes, floor_plan_area_id, created_at, updated_at
FROM electrical_breakers
WHERE id = $1
`

func (q *Queries) GetBreaker(ctx context.Context, id string) (ElectricalBreaker, error) {
	row := q.db.QueryRow(ctx, getBreaker, id)
	var i ElectricalBreaker
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.Slot,
		&i.Label,
		&i.Amps,
		&i.BreakerType,
		&i.IsGfci,
		&i.IsAfci,
		&i.Notes,
		&i.FloorPlanAreaID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBreakerPanelID = `-- name: GetBreakerPanelID :one
SELECT panel_id FROM electrical_breakers WHERE id = $1
`

func (q *Queries) GetBreakerPanelID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getBreakerPanelID, id)
	var panel_id string
	err := row.Scan(&panel_id)
	return panel_id, err
}

const listBreakers = `-- name: ListBreakers :many
SELECT id, panel_id, slot, label, amps,
       breaker_type, is_gfci, is_afci, notes, floor_plan_area_id, created_at, updated_at
FROM electrical_breakers
WHERE panel_id = $1 ORDER BY slot
`

func (q *Queries) ListBreakers(ctx context.Context, panelID string) ([]ElectricalBreaker, error) {
	rows, err := q.db.Query(ctx, listBreakers, panelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ElectricalBreaker
	for rows.Next() {
		var i ElectricalBreaker
		if err := rows.Scan(
			&i.ID,
			&i.PanelID,
			&i.Slot,
			&i.Label,
			&i.Amps,
			&i.BreakerType,
			&i.IsGfci,
			&i.IsAfci,
			&i.Notes,
			&i.FloorPlanAreaID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBreaker = `-- name: UpdateBreaker :one
UPDATE electrical_breakers
SET label = $2, amps = $3, breaker_type = $4, is_gfci = $5, is_afci = $6,
    notes = $7, floor_plan_area_id = $8, updated_at = NOW()
WHERE id = $1
RETURNING id, panel_id, slot, label, amps, breaker_type, is_gfci, is_afci, notes, floor_plan_area_id, created_at, updated_at
`

type UpdateBreakerParams struct {
	ID              string      `json:"id"`
	Label           *string     `json:"label"`
	Amps            pgtype.Int4 `json:"amps"`
	BreakerType     string      `json:"breaker_type"`
	IsGfci          bool        `json:"is_gfci"`
	IsAfci          bool        `json:"is_afci"`
	Notes           *string     `json:"notes"`
	FloorPlanAreaID *string     `json:"floor_plan_area_id"`
}

func (q *Queries) UpdateBreaker(ctx context.Context, arg UpdateBreakerParams) (ElectricalBreaker, error) {
	row := q.db.QueryRow(ctx, updateBreaker,
		arg.ID,
		arg.Label,
		arg.Amps,
		arg.BreakerType,
		arg.IsGfci,
		arg.IsAfci,
		arg.Notes,
		arg.FloorPlanAreaID,
	)
	var i ElectricalBreaker
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.Slot,
		&i.Label,
		&i.Amps,
		&i.BreakerType,
		&i.IsGfci,
		&i.IsAfci,
		&i.Notes,
		&i.FloorPlanAreaID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
