// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: electrical_panels.sql

package store

import (
	"context"
)

const countSubpanels = `-- name: CountSubpanels :one
SELECT COUNT(*) FROM electrical_panels WHERE parent_panel_id = $1
`

func (q *Queries) CountSubpanels(ctx context.Context, parentPanelID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countSubpanels, parentPanelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPanel = `-- name: CreatePanel :one
INSERT INTO electrical_panels (home_id, name, total_amps, total_slots, location_note, parent_panel_id, fed_by_breaker_id, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, home_id, name, total_amps, total_slots, location_note, parent_panel_id, fed_by_breaker_id, sort_order, created_at, updated_at
`

type CreatePanelParams struct {
	HomeID         string  `json:"home_id"`
	Name           string  `json:"name"`
	TotalAmps      int32   `json:"total_amps"`
	TotalSlots     int32   `json:"total_slots"`
	LocationNote   *string `json:"location_note"`
	ParentPanelID  *string `json:"parent_panel_id"`
	FedByBreakerID *string `json:"fed_by_breaker_id"`
	SortOrder      int32   `json:"sort_order"`
}

func (q *Queries) CreatePanel(ctx context.Context, arg CreatePanelParams) (ElectricalPanel, error) {
	row := q.db.QueryRow(ctx, createPanel,
		arg.HomeID,
		arg.Name,
		arg.TotalAmps,
		arg.TotalSlots,
		arg.LocationNote,
		arg.ParentPanelID,
		arg.FedByBreakerID,
		arg.SortOrder,
	)
	var i ElectricalPanel
	err := row.Scan(
		&i.ID,
		&i.HomeID,
		&i.Name,
		&i.TotalAmps,
		&i.TotalSlots,
		&i.LocationNote,
		&i.ParentPanelID,
		&i.FedByBreakerID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePanel = `-- name: DeletePanel :exec
DELETE FROM electrical_panels WHERE id = $1
`

func (q *Queries) DeletePanel(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePanel, id)
	return err
}

const getPanel = `-- name: GetPanel :one
SELECT id, home_id, name, total_amps, total_slots,
       location_note, parent_panel_id, fed_by_breaker_id, sort_order, created_at, updated_at
FROM electrical_panels
WHERE id = $1
`

func (q *Queries) GetPanel(ctx context.Context, id string) (ElectricalPanel, error) {
	row := q.db.QueryRow(ctx, getPanel, id)
	var i ElectricalPanel
	err := row.Scan(
		&i.ID,
		&i.HomeID,
		&i.Name,
		&i.TotalAmps,
		&i.TotalSlots,
		&i.LocationNote,
		&i.ParentPanelID,
		&i.FedByBreakerID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPanelHomeID = `-- name: GetPanelHomeID :one
SELECT home_id FROM electrical_panels WHERE id = $1
`

func (q *Queries) GetPanelHomeID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getPanelHomeID, id)
	var home_id string
	err := row.Scan(&home_id)
	return home_id, err
}

const listPanels = `-- name: ListPanels :many
SELECT id, home_id, name, total_amps, total_slots,
       location_note, parent_panel_id, fed_by_breaker_id, sort_order, created_at, updated_at
FROM electrical_panels
WHERE home_id = $1 ORDER BY sort_order, created_at
`

func (q *Queries) ListPanels(ctx context.Context, homeID string) ([]ElectricalPanel, error) {
	rows, err := q.db.Query(ctx, listPanels, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ElectricalPanel
	for rows.Next() {
		var i ElectricalPanel
		if err := rows.Scan(
			&i.ID,
			&i.HomeID,
			&i.Name,
			&i.TotalAmps,
			&i.TotalSlots,
			&i.LocationNote,
			&i.ParentPanelID,
			&i.FedByBreakerID,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePanel = `-- name: UpdatePanel :one
UPDATE electrical_panels
SET name = $2, total_amps = $3, total_slots = $4, location_note = $5,
    parent_panel_id = $6, fed_by_breaker_id = $7, sort_order = $8, updated_at = NOW()
WHERE id = $1
RETURNING id, home_id, name, total_amps, total_slots, location_note, parent_panel_id, fed_by_breaker_id, sort_order, created_at, updated_at
`

type UpdatePanelParams struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	TotalAmps      int32   `json:"total_amps"`
	TotalSlots     int32   `json:"total_slots"`
	LocationNote   *string `json:"location_note"`
	ParentPanelID  *string `json:"parent_panel_id"`
	FedByBreakerID *string `json:"fed_by_breaker_id"`
	SortOrder      int32   `json:"sort_order"`
}

func (q *Queries) UpdatePanel(ctx context.Context, arg UpdatePanelParams) (ElectricalPanel, error) {
	row := q.db.QueryRow(ctx, updatePanel,
		arg.ID,
		arg.Name,
		arg.TotalAmps,
		arg.TotalSlots,
		arg.LocationNote,
		arg.ParentPanelID,
		arg.FedByBreakerID,
		arg.SortOrder,
	)
	var i ElectricalPanel
	err := row.Scan(
		&i.ID,
		&i.HomeID,
		&i.Name,
		&i.TotalAmps,
		&i.TotalSlots,
		&i.LocationNote,
		&i.ParentPanelID,
		&i.FedByBreakerID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
