// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: floor_plan_areas.sql

package store

import (
	"context"
)

const createFloorPlanArea = `-- name: CreateFloorPlanArea :one
INSERT INTO floor_plan_areas (home_id, document_id, name, color, geometry)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, home_id, document_id, name, color, geometry, created_at, updated_at
`

type CreateFloorPlanAreaParams struct {
	HomeID     string  `json:"home_id"`
	DocumentID *string `json:"document_id"`
	Name       string  `json:"name"`
	Color      string  `json:"color"`
	Geometry   []byte  `json:"geometry"`
}

func (q *Queries) CreateFloorPlanArea(ctx context.Context, arg CreateFloorPlanAreaParams) (FloorPlanArea, error) {
	row := q.db.QueryRow(ctx, createFloorPlanArea,
		arg.HomeID,
		arg.DocumentID,
		arg.Name,
		arg.Color,
		arg.Geometry,
	)
	var i FloorPlanArea
	err := row.Scan(
		&i.ID,
		&i.HomeID,
		&i.DocumentID,
		&i.Name,
		&i.Color,
		&i.Geometry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFloorPlanArea = `-- name: DeleteFloorPlanArea :exec
DELETE FROM floor_plan_areas WHERE id = $1
`

func (q *Queries) DeleteFloorPlanArea(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteFloorPlanArea, id)
	return err
}

const getFloorPlanAreaHomeID = `-- name: GetFloorPlanAreaHomeID :one
SELECT home_id FROM floor_plan_areas WHERE id = $1
`

func (q *Queries) GetFloorPlanAreaHomeID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getFloorPlanAreaHomeID, id)
	var home_id string
	err := row.Scan(&home_id)
	return home_id, err
}

const listFloorPlanAreas = `-- name: ListFloorPlanAreas :many
SELECT id, home_id, document_id, name, color, geometry, created_at, updated_at
FROM floor_plan_areas WHERE home_id = $1 ORDER BY name
`

func (q *Queries) ListFloorPlanAreas(ctx context.Context, homeID string) ([]FloorPlanArea, error) {
	rows, err := q.db.Query(ctx, listFloorPlanAreas, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FloorPlanArea
	for rows.Next() {
		var i FloorPlanArea
		if err := rows.Scan(
			&i.ID,
			&i.HomeID,
			&i.DocumentID,
			&i.Name,
			&i.Color,
			&i.Geometry,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFloorPlanArea = `-- name: UpdateFloorPlanArea :one
UPDATE floor_plan_areas SET name = $2, color = $3, geometry = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, home_id, document_id, name, color, geometry, created_at, updated_at
`

type UpdateFloorPlanAreaParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Color    string `json:"color"`
	Geometry []byte `json:"geometry"`
}

func (q *Queries) UpdateFloorPlanArea(ctx context.Context, arg UpdateFloorPlanAreaParams) (FloorPlanArea, error) {
	row := q.db.QueryRow(ctx, updateFloorPlanArea,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Geometry,
	)
	var i FloorPlanArea
	err := row.Scan(
		&i.ID,
		&i.HomeID,
		&i.DocumentID,
		&i.Name,
		&i.Color,
		&i.Geometry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
