// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: floor_plan_shapes.sql

package store

import (
	"context"
)

const createFloorPlanShape = `-- name: CreateFloorPlanShape :one
INSERT INTO floor_plan_shapes (home_id, document_id, item_id, label, color, geometry)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, home_id, document_id, item_id, label, color, geometry, created_at, updated_at
`

type CreateFloorPlanShapeParams struct {
	HomeID     string  `json:"home_id"`
	DocumentID *string `json:"document_id"`
	ItemID     *string `json:"item_id"`
	Label      *string `json:"label"`
	Color      string  `json:"color"`
	Geometry   []byte  `json:"geometry"`
}

func (q *Queries) CreateFloorPlanShape(ctx context.Context, arg CreateFloorPlanShapeParams) (FloorPlanShape, error) {
	row := q.db.QueryRow(ctx, createFloorPlanShape,
		arg.HomeID,
		arg.DocumentID,
		arg.ItemID,
		arg.Label,
		arg.Color,
		arg.Geometry,
	)
	var i FloorPlanShape
	err := row.Scan(
		&i.ID,
		&i.HomeID,
		&i.DocumentID,
		&i.ItemID,
		&i.Label,
		&i.Color,
		&i.Geometry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFloorPlanShape = `-- name: DeleteFloorPlanShape :exec
DELETE FROM floor_plan_shapes WHERE id = $1
`

func (q *Queries) DeleteFloorPlanShape(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteFloorPlanShape, id)
	return err
}

const getFloorPlanShape = `-- name: GetFloorPlanShape :one
SELECT id, home_id, document_id, item_id, label, color, geometry, created_at, updated_at
FROM floor_plan_shapes WHERE id = $1
`

func (q *Queries) GetFloorPlanShape(ctx context.Context, id string) (FloorPlanShape, error) {
	row := q.db.QueryRow(ctx, getFloorPlanShape, id)
	var i FloorPlanShape
	err := row.Scan(
		&i.ID,
		&i.HomeID,
		&i.DocumentID,
		&i.ItemID,
		&i.Label,
		&i.Color,
		&i.Geometry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFloorPlanShapeHomeID = `-- name: GetFloorPlanShapeHomeID :one
SELECT home_id FROM floor_plan_shapes WHERE id = $1
`

func (q *Queries) GetFloorPlanShapeHomeID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getFloorPlanShapeHomeID, id)
	var home_id string
	err := row.Scan(&home_id)
	return home_id, err
}

const listFloorPlanShapes = `-- name: ListFloorPlanShapes :many
SELECT id, home_id, document_id, item_id, label, color, geometry, created_at, updated_at
FROM floor_plan_shapes WHERE home_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListFloorPlanShapes(ctx context.Context, homeID string) ([]FloorPlanShape, error) {
	rows, err := q.db.Query(ctx, listFloorPlanShapes, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FloorPlanShape
	for rows.Next() {
		var i FloorPlanShape
		if err := rows.Scan(
			&i.ID,
			&i.HomeID,
			&i.DocumentID,
			&i.ItemID,
			&i.Label,
			&i.Color,
			&i.Geometry,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFloorPlanShape = `-- name: UpdateFloorPlanShape :one
UPDATE floor_plan_shapes
SET document_id = $2, item_id = $3, label = $4, color = $5, geometry = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, home_id, document_id, item_id, label, color, geometry, created_at, updated_at
`

type UpdateFloorPlanShapeParams struct {
	ID         string  `json:"id"`
	DocumentID *string `json:"document_id"`
	ItemID     *string `json:"item_id"`
	Label      *string `json:"label"`
	Color      string  `json:"color"`
	Geometry   []byte  `json:"geometry"`
}

func (q *Queries) UpdateFloorPlanShape(ctx context.Context, arg UpdateFloorPlanShapeParams) (FloorPlanShape, error) {
	row := q.db.QueryRow(ctx, updateFloorPlanShape,
		arg.ID,
		arg.DocumentID,
		arg.ItemID,
		arg.Label,
		arg.Color,
		arg.Geometry,
	)
	var i FloorPlanShape
	err := row.Scan(
		&i.ID,
		&i.HomeID,
		&i.DocumentID,
		&i.ItemID,
		&i.Label,
		&i.Color,
		&i.Geometry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
