// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: homes.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHomeOwners = `-- name: CountHomeOwners :one
SELECT COUNT(*) FROM home_members WHERE home_id = $1 AND role = 'owner'
`

func (q *Queries) CountHomeOwners(ctx context.Context, homeID string) (int64, error) {
	row := q.db.QueryRow(ctx, countHomeOwners, homeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFirstHome = `-- name: CreateFirstHome :one
INSERT INTO homes (name) VALUES ($1) RETURNING id
`

func (q *Queries) CreateFirstHome(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRow(ctx, createFirstHome, name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createHome = `-- name: CreateHome :one
INSERT INTO homes (name, address_street, address_city, address_state, address_zip, address_country,
                   property_type, year_built, sqft, acreage, notes,
                   purchase_price, purchased_at, estimated_value,
                   mortgage_lender, mortgage_notes,
                   hoa_name, hoa_contact, hoa_monthly_dues)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19)
RETURNING id
`

type CreateHomeParams struct {
	Name           string         `json:"name"`
	AddressStreet  *string        `json:"address_street"`
	AddressCity    *string        `json:"address_city"`
	AddressState   *string        `json:"address_state"`
	AddressZip     *string        `json:"address_zip"`
	AddressCountry *string        `json:"address_country"`
	PropertyType   *string        `json:"property_type"`
	YearBuilt      pgtype.Int4    `json:"year_built"`
	Sqft           pgtype.Numeric `json:"sqft"`
	Acreage        pgtype.Numeric `json:"acreage"`
	Notes          *string        `json:"notes"`
	PurchasePrice  pgtype.Numeric `json:"purchase_price"`
	PurchasedAt    *time.Time     `json:"purchased_at"`
	EstimatedValue pgtype.Numeric `json:"estimated_value"`
	MortgageLender *string        `json:"mortgage_lender"`
	MortgageNotes  *string        `json:"mortgage_notes"`
	HoaName        *string        `json:"hoa_name"`
	HoaContact     *string        `json:"hoa_contact"`
	HoaMonthlyDues pgtype.Numeric `json:"hoa_monthly_dues"`
}

func (q *Queries) CreateHome(ctx context.Context, arg CreateHomeParams) (string, error) {
	row := q.db.QueryRow(ctx, createHome,
		arg.Name,
		arg.AddressStreet,
		arg.AddressCity,
		arg.AddressState,
		arg.AddressZip,
		arg.AddressCountry,
		arg.PropertyType,
		arg.YearBuilt,
		arg.Sqft,
		arg.Acreage,
		arg.Notes,
		arg.PurchasePrice,
		arg.PurchasedAt,
		arg.EstimatedValue,
		arg.MortgageLender,
		arg.MortgageNotes,
		arg.HoaName,
		arg.HoaContact,
		arg.HoaMonthlyDues,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createHomeDocument = `-- name: CreateHomeDocument :one
INSERT INTO home_documents (home_id, filename, content_type, file_path, size, document_type)
VALUES ($1, $2, $3, 'pending', 0, $4)
RETURNING id, home_id, filename, content_type, file_path, size, document_type, created_at
`

type CreateHomeDocumentParams struct {
	HomeID       string  `json:"home_id"`
	Filename     string  `json:"filename"`
	ContentType  string  `json:"content_type"`
	DocumentType *string `json:"document_type"`
}

type CreateHomeDocumentRow struct {
	ID           string             `json:"id"`
	HomeID       string             `json:"home_id"`
	Filename     string             `json:"filename"`
	ContentType  string             `json:"content_type"`
	FilePath     string             `json:"file_path"`
	Size         int64              `json:"size"`
	DocumentType *string            `json:"document_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateHomeDocument(ctx context.Context, arg CreateHomeDocumentParams) (CreateHomeDocumentRow, error) {
	row := q.db.QueryRow(ctx, createHomeDocument,
		arg.HomeID,
		arg.Filename,
		arg.ContentType,
		arg.DocumentType,
	)
	var i CreateHomeDocumentRow
	err := row.Scan(
		&i.ID,
		&i.HomeID,
		&i.Filename,
		&i.ContentType,
		&i.FilePath,
		&i.Size,
		&i.DocumentType,
		&i.CreatedAt,
	)
	return i, err
}

const createHomePhoto = `-- name: CreateHomePhoto :one
INSERT INTO home_photos (home_id, filename, content_type, file_path)
VALUES ($1, $2, $3, 'pending')
RETURNING id, home_id, filename, content_type, file_path, created_at
`

type CreateHomePhotoParams struct {
	HomeID      string `json:"home_id"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
}

func (q *Queries) CreateHomePhoto(ctx context.Context, arg CreateHomePhotoParams) (HomePhoto, error) {
	row := q.db.QueryRow(ctx, createHomePhoto, arg.HomeID, arg.Filename, arg.ContentType)
	var i HomePhoto
	err := row.Scan(
		&i.ID,
		&i.HomeID,
		&i.Filename,
		&i.ContentType,
		&i.FilePath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHome = `-- name: DeleteHome :exec
DELETE FROM homes WHERE id = $1
`

func (q *Queries) DeleteHome(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteHome, id)
	return err
}

const deleteHomeDocument = `-- name: DeleteHomeDocument :exec
DELETE FROM home_documents WHERE id = $1
`

func (q *Queries) DeleteHomeDocument(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteHomeDocument, id)
	return err
}

const deleteHomeMember = `-- name: DeleteHomeMember :exec
DELETE FROM home_members WHERE home_id = $1 AND user_id = $2
`

type DeleteHomeMemberParams struct {
	HomeID string `json:"home_id"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) DeleteHomeMember(ctx context.Context, arg DeleteHomeMemberParams) error {
	_, err := q.db.Exec(ctx, deleteHomeMember, arg.HomeID, arg.UserID)
	return err
}

const deleteHomePhoto = `-- name: DeleteHomePhoto :exec
DELETE FROM home_photos WHERE id = $1
`

func (q *Queries) DeleteHomePhoto(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteHomePhoto, id)
	return err
}

const getHomeDocumentFilePath = `-- name: GetHomeDocumentFilePath :one
SELECT file_path FROM home_documents WHERE id = $1 AND home_id = $2
`

type GetHomeDocumentFilePathParams struct {
	ID     string `json:"id"`
	HomeID string `json:"home_id"`
}

func (q *Queries) GetHomeDocumentFilePath(ctx context.Context, arg GetHomeDocumentFilePathParams) (string, error) {
	row := q.db.QueryRow(ctx, getHomeDocumentFilePath, arg.ID, arg.HomeID)
	var file_path string
	err := row.Scan(&file_path)
	return file_path, err
}

const getHomeForUser = `-- name: GetHomeForUser :one
SELECT h.id, h.name,
       h.address_street, h.address_city, h.address_state, h.address_zip, h.address_country,
       h.property_type, h.year_built, h.sqft, h.acreage, h.notes,
       h.purchase_price, h.purchased_at, h.estimated_value,
       h.mortgage_lender, h.mortgage_notes,
       h.hoa_name, h.hoa_contact, h.hoa_monthly_dues,
       hm.role, h.created_at, h.updated_at
FROM homes h
JOIN home_members hm ON hm.home_id = h.id AND hm.user_id = $1
WHERE h.id = $2
`

type GetHomeForUserParams struct {
	UserID int64  `json:"user_id"`
	ID     string `json:"id"`
}

type GetHomeForUserRow struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	AddressStreet  *string            `json:"address_street"`
	AddressCity    *string            `json:"address_city"`
	AddressState   *string            `json:"address_state"`
	AddressZip     *string            `json:"address_zip"`
	AddressCountry *string            `json:"address_country"`
	PropertyType   *string            `json:"property_type"`
	YearBuilt      pgtype.Int4        `json:"year_built"`
	Sqft           pgtype.Numeric     `json:"sqft"`
	Acreage        pgtype.Numeric     `json:"acreage"`
	Notes          *string            `json:"notes"`
	PurchasePrice  pgtype.Numeric     `json:"purchase_price"`
	PurchasedAt    *time.Time         `json:"purchased_at"`
	EstimatedValue pgtype.Numeric     `json:"estimated_value"`
	MortgageLender *string            `json:"mortgage_lender"`
	MortgageNotes  *string            `json:"mortgage_notes"`
	HoaName        *string            `json:"hoa_name"`
	HoaContact     *string            `json:"hoa_contact"`
	HoaMonthlyDues pgtype.Numeric     `json:"hoa_monthly_dues"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetHomeForUser(ctx context.Context, arg GetHomeForUserParams) (GetHomeForUserRow, error) {
	row := q.db.QueryRow(ctx, getHomeForUser, arg.UserID, arg.ID)
	var i GetHomeForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZip,
		&i.AddressCountry,
		&i.PropertyType,
		&i.YearBuilt,
		&i.Sqft,
		&i.Acreage,
		&i.Notes,
		&i.PurchasePrice,
		&i.PurchasedAt,
		&i.EstimatedValue,
		&i.MortgageLender,
		&i.MortgageNotes,
		&i.HoaName,
		&i.HoaContact,
		&i.HoaMonthlyDues,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHomeMemberRole = `-- name: GetHomeMemberRole :one
SELECT role FROM home_members WHERE home_id = $1 AND user_id = $2
`

type GetHomeMemberRoleParams struct {
	HomeID string `json:"home_id"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) GetHomeMemberRole(ctx context.Context, arg GetHomeMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getHomeMemberRole, arg.HomeID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getHomePhotoFilePath = `-- name: GetHomePhotoFilePath :one
SELECT file_path FROM home_photos WHERE id = $1 AND home_id = $2
`

type GetHomePhotoFilePathParams struct {
	ID     string `json:"id"`
	HomeID string `json:"home_id"`
}

func (q *Queries) GetHomePhotoFilePath(ctx context.Context, arg GetHomePhotoFilePathParams) (string, error) {
	row := q.db.QueryRow(ctx, getHomePhotoFilePath, arg.ID, arg.HomeID)
	var file_path string
	err := row.Scan(&file_path)
	return file_path, err
}

const listHomeDocuments = `-- name: ListHomeDocuments :many
SELECT id, home_id, filename, content_type, file_path, size, document_type, floor_level, created_at
FROM home_documents WHERE home_id = $1
ORDER BY (document_type = 'floor_plan') DESC, created_at ASC
`

func (q *Queries) ListHomeDocuments(ctx context.Context, homeID string) ([]HomeDocument, error) {
	rows, err := q.db.Query(ctx, listHomeDocuments, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeDocument
	for rows.Next() {
		var i HomeDocument
		if err := rows.Scan(
			&i.ID,
			&i.HomeID,
			&i.Filename,
			&i.ContentType,
			&i.FilePath,
			&i.Size,
			&i.DocumentType,
			&i.FloorLevel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeMembers = `-- name: ListHomeMembers :many
SELECT u.id, u.name, u.email, hm.role, hm.created_at
FROM home_members hm
JOIN users u ON u.id = hm.user_id
WHERE hm.home_id = $1
ORDER BY hm.created_at ASC
`

type ListHomeMembersRow struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListHomeMembers(ctx context.Context, homeID string) ([]ListHomeMembersRow, error) {
	rows, err := q.db.Query(ctx, listHomeMembers, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHomeMembersRow
	for rows.Next() {
		var i ListHomeMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomePhotos = `-- name: ListHomePhotos :many
SELECT id, home_id, filename, content_type, file_path, created_at
FROM home_photos WHERE home_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListHomePhotos(ctx context.Context, homeID string) ([]HomePhoto, error) {
	rows, err := q.db.Query(ctx, listHomePhotos, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomePhoto
	for rows.Next() {
		var i HomePhoto
		if err := rows.Scan(
			&i.ID,
			&i.HomeID,
			&i.Filename,
			&i.ContentType,
			&i.FilePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomesForUser = `-- name: ListHomesForUser :many
SELECT h.id, h.name,
       h.address_street, h.address_city, h.address_state, h.address_zip, h.address_country,
       h.property_type, h.year_built, h.sqft, h.acreage, h.notes,
       h.purchase_price, h.purchased_at, h.estimated_value,
       h.mortgage_lender, h.mortgage_notes,
       h.hoa_name, h.hoa_contact, h.hoa_monthly_dues,
       hm.role, h.created_at, h.updated_at
FROM homes h
JOIN home_members hm ON hm.home_id = h.id AND hm.user_id = $1
ORDER BY h.name
`

type ListHomesForUserRow struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	AddressStreet  *string            `json:"address_street"`
	AddressCity    *string            `json:"address_city"`
	AddressState   *string            `json:"address_state"`
	AddressZip     *string            `json:"address_zip"`
	AddressCountry *string            `json:"address_country"`
	PropertyType   *string            `json:"property_type"`
	YearBuilt      pgtype.Int4        `json:"year_built"`
	Sqft           pgtype.Numeric     `json:"sqft"`
	Acreage        pgtype.Numeric     `json:"acreage"`
	Notes          *string            `json:"notes"`
	PurchasePrice  pgtype.Numeric     `json:"purchase_price"`
	PurchasedAt    *time.Time         `json:"purchased_at"`
	EstimatedValue pgtype.Numeric     `json:"estimated_value"`
	MortgageLender *string            `json:"mortgage_lender"`
	MortgageNotes  *string            `json:"mortgage_notes"`
	HoaName        *string            `json:"hoa_name"`
	HoaContact     *string            `json:"hoa_contact"`
	HoaMonthlyDues pgtype.Numeric     `json:"hoa_monthly_dues"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListHomesForUser(ctx context.Context, userID int64) ([]ListHomesForUserRow, error) {
	rows, err := q.db.Query(ctx, listHomesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHomesForUserRow
	for rows.Next() {
		var i ListHomesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AddressStreet,
			&i.AddressCity,
			&i.AddressState,
			&i.AddressZip,
			&i.AddressCountry,
			&i.PropertyType,
			&i.YearBuilt,
			&i.Sqft,
			&i.Acreage,
			&i.Notes,
			&i.PurchasePrice,
			&i.PurchasedAt,
			&i.EstimatedValue,
			&i.MortgageLender,
			&i.MortgageNotes,
			&i.HoaName,
			&i.HoaContact,
			&i.HoaMonthlyDues,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHome = `-- name: UpdateHome :exec
UPDATE homes SET name=$2, address_street=$3, address_city=$4, address_state=$5,
                 address_zip=$6, address_country=$7, property_type=$8,
                 year_built=$9, sqft=$10, acreage=$11, notes=$12,
                 purchase_price=$13, purchased_at=$14, estimated_value=$15,
                 mortgage_lender=$16, mortgage_notes=$17,
                 hoa_name=$18, hoa_contact=$19, hoa_monthly_dues=$20, updated_at=NOW()
WHERE id=$1
`

type UpdateHomeParams struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	AddressStreet  *string        `json:"address_street"`
	AddressCity    *string        `json:"address_city"`
	AddressState   *string        `json:"address_state"`
	AddressZip     *string        `json:"address_zip"`
	AddressCountry *string        `json:"address_country"`
	PropertyType   *string        `json:"property_type"`
	YearBuilt      pgtype.Int4    `json:"year_built"`
	Sqft           pgtype.Numeric `json:"sqft"`
	Acreage        pgtype.Numeric `json:"acreage"`
	Notes          *string        `json:"notes"`
	PurchasePrice  pgtype.Numeric `json:"purchase_price"`
	PurchasedAt    *time.Time     `json:"purchased_at"`
	EstimatedValue pgtype.Numeric `json:"estimated_value"`
	MortgageLender *string        `json:"mortgage_lender"`
	MortgageNotes  *string        `json:"mortgage_notes"`
	HoaName        *string        `json:"hoa_name"`
	HoaContact     *string        `json:"hoa_contact"`
	HoaMonthlyDues pgtype.Numeric `json:"hoa_monthly_dues"`
}

func (q *Queries) UpdateHome(ctx context.Context, arg UpdateHomeParams) error {
	_, err := q.db.Exec(ctx, updateHome,
		arg.ID,
		arg.Name,
		arg.AddressStreet,
		arg.AddressCity,
		arg.AddressState,
		arg.AddressZip,
		arg.AddressCountry,
		arg.PropertyType,
		arg.YearBuilt,
		arg.Sqft,
		arg.Acreage,
		arg.Notes,
		arg.PurchasePrice,
		arg.PurchasedAt,
		arg.EstimatedValue,
		arg.MortgageLender,
		arg.MortgageNotes,
		arg.HoaName,
		arg.HoaContact,
		arg.HoaMonthlyDues,
	)
	return err
}

const updateHomeDocumentFloorLevel = `-- name: UpdateHomeDocumentFloorLevel :exec
UPDATE home_documents SET floor_level = $1 WHERE id = $2 AND home_id = $3
`

type UpdateHomeDocumentFloorLevelParams struct {
	FloorLevel pgtype.Int4 `json:"floor_level"`
	ID         string      `json:"id"`
	HomeID     string      `json:"home_id"`
}

func (q *Queries) UpdateHomeDocumentFloorLevel(ctx context.Context, arg UpdateHomeDocumentFloorLevelParams) error {
	_, err := q.db.Exec(ctx, updateHomeDocumentFloorLevel, arg.FloorLevel, arg.ID, arg.HomeID)
	return err
}

const updateHomeDocumentPath = `-- name: UpdateHomeDocumentPath :exec
UPDATE home_documents SET file_path = $1, size = $2 WHERE id = $3
`

type UpdateHomeDocumentPathParams struct {
	FilePath string `json:"file_path"`
	Size     int64  `json:"size"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateHomeDocumentPath(ctx context.Context, arg UpdateHomeDocumentPathParams) error {
	_, err := q.db.Exec(ctx, updateHomeDocumentPath, arg.FilePath, arg.Size, arg.ID)
	return err
}

const updateHomePhotoPath = `-- name: UpdateHomePhotoPath :exec
UPDATE home_photos SET file_path = $1 WHERE id = $2
`

type UpdateHomePhotoPathParams struct {
	FilePath string `json:"file_path"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateHomePhotoPath(ctx context.Context, arg UpdateHomePhotoPathParams) error {
	_, err := q.db.Exec(ctx, updateHomePhotoPath, arg.FilePath, arg.ID)
	return err
}

const upsertHomeMember = `-- name: UpsertHomeMember :exec
INSERT INTO home_members (home_id, user_id, role) VALUES ($1, $2, $3)
ON CONFLICT (home_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type UpsertHomeMemberParams struct {
	HomeID string `json:"home_id"`
	UserID int64  `json:"user_id"`
	Role   string `json:"role"`
}

func (q *Queries) UpsertHomeMember(ctx context.Context, arg UpsertHomeMemberParams) error {
	_, err := q.db.Exec(ctx, upsertHomeMember, arg.HomeID, arg.UserID, arg.Role)
	return err
}
