// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllExpiringWarranties = `-- name: CountAllExpiringWarranties :one
SELECT COUNT(*) FROM items
WHERE tier != 'quick'
  AND warranty_expires_at IS NOT NULL AND warranty_expires_at <= NOW() + INTERVAL '30 days'
`

func (q *Queries) CountAllExpiringWarranties(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllExpiringWarranties)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllItems = `-- name: CountAllItems :one
SELECT COUNT(*) FROM items WHERE tier != 'quick'
`

func (q *Queries) CountAllItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExpiringWarrantiesByHome = `-- name: CountExpiringWarrantiesByHome :one
SELECT COUNT(*) FROM items
WHERE home_id = $1 AND tier != 'quick'
  AND warranty_expires_at IS NOT NULL AND warranty_expires_at <= NOW() + INTERVAL '30 days'
`

func (q *Queries) CountExpiringWarrantiesByHome(ctx context.Context, homeID string) (int64, error) {
	row := q.db.QueryRow(ctx, countExpiringWarrantiesByHome, homeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countItemsByHome = `-- name: CountItemsByHome :one
SELECT COUNT(*) FROM items WHERE home_id = $1 AND tier != 'quick'
`

func (q *Queries) CountItemsByHome(ctx context.Context, homeID string) (int64, error) {
	row := q.db.QueryRow(ctx, countItemsByHome, homeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (name, description, location_id, status, manufacturer, model, serial,
                   purchase_price, purchased_at, warranty, warranty_expires_at, insured, notes, asset_id, home_id,
                   tier, grid_row, grid_col)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18)
RETURNING id
`

type CreateItemParams struct {
	Name              string         `json:"name"`
	Description       *string        `json:"description"`
	LocationID        *string        `json:"location_id"`
	Status            string         `json:"status"`
	Manufacturer      *string        `json:"manufacturer"`
	Model             *string        `json:"model"`
	Serial            *string        `json:"serial"`
	PurchasePrice     pgtype.Numeric `json:"purchase_price"`
	PurchasedAt       *time.Time     `json:"purchased_at"`
	Warranty          *string        `json:"warranty"`
	WarrantyExpiresAt *time.Time     `json:"warranty_expires_at"`
	Insured           bool           `json:"insured"`
	Notes             *string        `json:"notes"`
	AssetID           *string        `json:"asset_id"`
	HomeID            string         `json:"home_id"`
	Tier              string         `json:"tier"`
	GridRow           pgtype.Int4    `json:"grid_row"`
	GridCol           pgtype.Int4    `json:"grid_col"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (string, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Name,
		arg.Description,
		arg.LocationID,
		arg.Status,
		arg.Manufacturer,
		arg.Model,
		arg.Serial,
		arg.PurchasePrice,
		arg.PurchasedAt,
		arg.Warranty,
		arg.WarrantyExpiresAt,
		arg.Insured,
		arg.Notes,
		arg.AssetID,
		arg.HomeID,
		arg.Tier,
		arg.GridRow,
		arg.GridCol,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const deleteItemCustomFields = `-- name: DeleteItemCustomFields :exec
DELETE FROM item_custom_fields WHERE item_id = $1
`

func (q *Queries) DeleteItemCustomFields(ctx context.Context, itemID string) error {
	_, err := q.db.Exec(ctx, deleteItemCustomFields, itemID)
	return err
}

const deleteItemLabels = `-- name: DeleteItemLabels :exec
DELETE FROM item_labels WHERE item_id = $1
`

func (q *Queries) DeleteItemLabels(ctx context.Context, itemID string) error {
	_, err := q.db.Exec(ctx, deleteItemLabels, itemID)
	return err
}

const getMaxGridCell = `-- name: GetMaxGridCell :one
SELECT COALESCE(MAX(grid_row), -1)::int AS max_row, COALESCE(MAX(grid_col), -1)::int AS max_col
FROM items WHERE location_id = $1
`

type GetMaxGridCellRow struct {
	MaxRow int32 `json:"max_row"`
	MaxCol int32 `json:"max_col"`
}

func (q *Queries) GetMaxGridCell(ctx context.Context, locationID *string) (GetMaxGridCellRow, error) {
	row := q.db.QueryRow(ctx, getMaxGridCell, locationID)
	var i GetMaxGridCellRow
	err := row.Scan(&i.MaxRow, &i.MaxCol)
	return i, err
}

const insertItemCustomField = `-- name: InsertItemCustomField :exec
INSERT INTO item_custom_fields (item_id, field_key, label, value, value_type, unit, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertItemCustomFieldParams struct {
	ItemID    string  `json:"item_id"`
	FieldKey  string  `json:"field_key"`
	Label     string  `json:"label"`
	Value     *string `json:"value"`
	ValueType string  `json:"value_type"`
	Unit      *string `json:"unit"`
	SortOrder int32   `json:"sort_order"`
}

func (q *Queries) InsertItemCustomField(ctx context.Context, arg InsertItemCustomFieldParams) error {
	_, err := q.db.Exec(ctx, insertItemCustomField,
		arg.ItemID,
		arg.FieldKey,
		arg.Label,
		arg.Value,
		arg.ValueType,
		arg.Unit,
		arg.SortOrder,
	)
	return err
}

const insertItemLabel = `-- name: InsertItemLabel :exec
INSERT INTO item_labels (item_id, label_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertItemLabelParams struct {
	ItemID  string `json:"item_id"`
	LabelID string `json:"label_id"`
}

func (q *Queries) InsertItemLabel(ctx context.Context, arg InsertItemLabelParams) error {
	_, err := q.db.Exec(ctx, insertItemLabel, arg.ItemID, arg.LabelID)
	return err
}

const listItemIDsMissingAssetID = `-- name: ListItemIDsMissingAssetID :many
SELECT id FROM items WHERE home_id = $1 AND tier != 'quick' AND asset_id IS NULL
`

func (q *Queries) ListItemIDsMissingAssetID(ctx context.Context, homeID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listItemIDsMissingAssetID, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setItemAssetID = `-- name: SetItemAssetID :exec
UPDATE items SET asset_id = $2, updated_at = NOW() WHERE id = $1
`

type SetItemAssetIDParams struct {
	ID      string  `json:"id"`
	AssetID *string `json:"asset_id"`
}

func (q *Queries) SetItemAssetID(ctx context.Context, arg SetItemAssetIDParams) error {
	_, err := q.db.Exec(ctx, setItemAssetID, arg.ID, arg.AssetID)
	return err
}

const updateItem = `-- name: UpdateItem :exec
UPDATE items SET name=$2, description=$3, location_id=$4, status=$5,
                 manufacturer=$6, model=$7, serial=$8,
                 purchase_price=$9, purchased_at=$10, warranty=$11, warranty_expires_at=$12,
                 insured=$13, notes=$14, asset_id=$15,
                 tier=$16, grid_row=$17, grid_col=$18, updated_at=NOW()
WHERE id=$1
`

type UpdateItemParams struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	Description       *string        `json:"description"`
	LocationID        *string        `json:"location_id"`
	Status            string         `json:"status"`
	Manufacturer      *string        `json:"manufacturer"`
	Model             *string        `json:"model"`
	Serial            *string        `json:"serial"`
	PurchasePrice     pgtype.Numeric `json:"purchase_price"`
	PurchasedAt       *time.Time     `json:"purchased_at"`
	Warranty          *string        `json:"warranty"`
	WarrantyExpiresAt *time.Time     `json:"warranty_expires_at"`
	Insured           bool           `json:"insured"`
	Notes             *string        `json:"notes"`
	AssetID           *string        `json:"asset_id"`
	Tier              string         `json:"tier"`
	GridRow           pgtype.Int4    `json:"grid_row"`
	GridCol           pgtype.Int4    `json:"grid_col"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.Exec(ctx, updateItem,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LocationID,
		arg.Status,
		arg.Manufacturer,
		arg.Model,
		arg.Serial,
		arg.PurchasePrice,
		arg.PurchasedAt,
		arg.Warranty,
		arg.WarrantyExpiresAt,
		arg.Insured,
		arg.Notes,
		arg.AssetID,
		arg.Tier,
		arg.GridRow,
		arg.GridCol,
	)
	return err
}
