// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllItems = `-- name: CountAllItems :one
SELECT COUNT(*) FROM items
`

func (q *Queries) CountAllItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countItemsByHome = `-- name: CountItemsByHome :one
SELECT COUNT(*) FROM items WHERE home_id = $1
`

func (q *Queries) CountItemsByHome(ctx context.Context, homeID string) (int64, error) {
	row := q.db.QueryRow(ctx, countItemsByHome, homeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (name, description, location_id, status, manufacturer, model, serial,
                   purchase_price, purchased_at, warranty, insured, notes, asset_id, home_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
RETURNING id
`

type CreateItemParams struct {
	Name          string         `json:"name"`
	Description   *string        `json:"description"`
	LocationID    *string        `json:"location_id"`
	Status        string         `json:"status"`
	Manufacturer  *string        `json:"manufacturer"`
	Model         *string        `json:"model"`
	Serial        *string        `json:"serial"`
	PurchasePrice pgtype.Numeric `json:"purchase_price"`
	PurchasedAt   *time.Time     `json:"purchased_at"`
	Warranty      *string        `json:"warranty"`
	Insured       bool           `json:"insured"`
	Notes         *string        `json:"notes"`
	AssetID       *string        `json:"asset_id"`
	HomeID        string         `json:"home_id"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (string, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Name,
		arg.Description,
		arg.LocationID,
		arg.Status,
		arg.Manufacturer,
		arg.Model,
		arg.Serial,
		arg.PurchasePrice,
		arg.PurchasedAt,
		arg.Warranty,
		arg.Insured,
		arg.Notes,
		arg.AssetID,
		arg.HomeID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const deleteItemLabels = `-- name: DeleteItemLabels :exec
DELETE FROM item_labels WHERE item_id = $1
`

func (q *Queries) DeleteItemLabels(ctx context.Context, itemID string) error {
	_, err := q.db.Exec(ctx, deleteItemLabels, itemID)
	return err
}

const insertItemLabel = `-- name: InsertItemLabel :exec
INSERT INTO item_labels (item_id, label_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertItemLabelParams struct {
	ItemID  string `json:"item_id"`
	LabelID string `json:"label_id"`
}

func (q *Queries) InsertItemLabel(ctx context.Context, arg InsertItemLabelParams) error {
	_, err := q.db.Exec(ctx, insertItemLabel, arg.ItemID, arg.LabelID)
	return err
}

const updateItem = `-- name: UpdateItem :exec
UPDATE items SET name=$2, description=$3, location_id=$4, status=$5,
                 manufacturer=$6, model=$7, serial=$8,
                 purchase_price=$9, purchased_at=$10, warranty=$11,
                 insured=$12, notes=$13, asset_id=$14, updated_at=NOW()
WHERE id=$1
`

type UpdateItemParams struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Description   *string        `json:"description"`
	LocationID    *string        `json:"location_id"`
	Status        string         `json:"status"`
	Manufacturer  *string        `json:"manufacturer"`
	Model         *string        `json:"model"`
	Serial        *string        `json:"serial"`
	PurchasePrice pgtype.Numeric `json:"purchase_price"`
	PurchasedAt   *time.Time     `json:"purchased_at"`
	Warranty      *string        `json:"warranty"`
	Insured       bool           `json:"insured"`
	Notes         *string        `json:"notes"`
	AssetID       *string        `json:"asset_id"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.Exec(ctx, updateItem,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LocationID,
		arg.Status,
		arg.Manufacturer,
		arg.Model,
		arg.Serial,
		arg.PurchasePrice,
		arg.PurchasedAt,
		arg.Warranty,
		arg.Insured,
		arg.Notes,
		arg.AssetID,
	)
	return err
}
