// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllLabels = `-- name: CountAllLabels :one
SELECT COUNT(*) FROM labels
`

func (q *Queries) CountAllLabels(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllLabels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLabelsByHome = `-- name: CountLabelsByHome :one
SELECT COUNT(*) FROM labels WHERE home_id = $1
`

func (q *Queries) CountLabelsByHome(ctx context.Context, homeID string) (int64, error) {
	row := q.db.QueryRow(ctx, countLabelsByHome, homeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (name, color, home_id) VALUES ($1, $2, $3)
RETURNING id, name, color, created_at, updated_at
`

type CreateLabelParams struct {
	Name   string `json:"name"`
	Color  string `json:"color"`
	HomeID string `json:"home_id"`
}

type CreateLabelRow struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (CreateLabelRow, error) {
	row := q.db.QueryRow(ctx, createLabel, arg.Name, arg.Color, arg.HomeID)
	var i CreateLabelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLabel = `-- name: DeleteLabel :exec
DELETE FROM labels WHERE id = $1
`

func (q *Queries) DeleteLabel(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLabel, id)
	return err
}

const getLabel = `-- name: GetLabel :one
SELECT lb.id, lb.name, lb.color, COUNT(il.item_id) AS item_count, lb.created_at, lb.updated_at
FROM labels lb
LEFT JOIN item_labels il ON il.label_id = lb.id
WHERE lb.id = $1
GROUP BY lb.id
`

type GetLabelRow struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	ItemCount int64              `json:"item_count"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetLabel(ctx context.Context, id string) (GetLabelRow, error) {
	row := q.db.QueryRow(ctx, getLabel, id)
	var i GetLabelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.ItemCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllLabels = `-- name: ListAllLabels :many
SELECT lb.id, lb.name, lb.color, COUNT(il.item_id) AS item_count, lb.created_at, lb.updated_at
FROM labels lb
LEFT JOIN item_labels il ON il.label_id = lb.id
GROUP BY lb.id ORDER BY lb.name
`

type ListAllLabelsRow struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	ItemCount int64              `json:"item_count"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAllLabels(ctx context.Context) ([]ListAllLabelsRow, error) {
	rows, err := q.db.Query(ctx, listAllLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllLabelsRow
	for rows.Next() {
		var i ListAllLabelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.ItemCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsByHome = `-- name: ListLabelsByHome :many
SELECT lb.id, lb.name, lb.color, COUNT(il.item_id) AS item_count, lb.created_at, lb.updated_at
FROM labels lb
LEFT JOIN item_labels il ON il.label_id = lb.id
WHERE lb.home_id = $1
GROUP BY lb.id ORDER BY lb.name
`

type ListLabelsByHomeRow struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	ItemCount int64              `json:"item_count"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListLabelsByHome(ctx context.Context, homeID string) ([]ListLabelsByHomeRow, error) {
	rows, err := q.db.Query(ctx, listLabelsByHome, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLabelsByHomeRow
	for rows.Next() {
		var i ListLabelsByHomeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.ItemCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLabel = `-- name: UpdateLabel :exec
UPDATE labels SET name = $2, color = $3, updated_at = NOW() WHERE id = $1
`

type UpdateLabelParams struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Color string `json:"color"`
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) error {
	_, err := q.db.Exec(ctx, updateLabel, arg.ID, arg.Name, arg.Color)
	return err
}
