// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllLocations = `-- name: CountAllLocations :one
SELECT COUNT(*) FROM locations
`

func (q *Queries) CountAllLocations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllLocations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLocationsByHome = `-- name: CountLocationsByHome :one
SELECT COUNT(*) FROM locations WHERE home_id = $1
`

func (q *Queries) CountLocationsByHome(ctx context.Context, homeID string) (int64, error) {
	row := q.db.QueryRow(ctx, countLocationsByHome, homeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (name, parent_id, description, home_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, parent_id, description, created_at, updated_at
`

type CreateLocationParams struct {
	Name        string  `json:"name"`
	ParentID    *string `json:"parent_id"`
	Description *string `json:"description"`
	HomeID      string  `json:"home_id"`
}

type CreateLocationRow struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	ParentID    *string            `json:"parent_id"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (CreateLocationRow, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.Name,
		arg.ParentID,
		arg.Description,
		arg.HomeID,
	)
	var i CreateLocationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const getLocation = `-- name: GetLocation :one
SELECT l.id, l.name, l.parent_id, l.description,
       COUNT(i.id) AS item_count, l.created_at, l.updated_at
FROM locations l
LEFT JOIN items i ON i.location_id = l.id
WHERE l.id = $1
GROUP BY l.id
`

type GetLocationRow struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	ParentID    *string            `json:"parent_id"`
	Description *string            `json:"description"`
	ItemCount   int64              `json:"item_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetLocation(ctx context.Context, id string) (GetLocationRow, error) {
	row := q.db.QueryRow(ctx, getLocation, id)
	var i GetLocationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Description,
		&i.ItemCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllLocations = `-- name: ListAllLocations :many
SELECT l.id, l.name, l.parent_id, l.description,
       COUNT(i.id) AS item_count, l.created_at, l.updated_at
FROM locations l
LEFT JOIN items i ON i.location_id = l.id
GROUP BY l.id ORDER BY l.name
`

type ListAllLocationsRow struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	ParentID    *string            `json:"parent_id"`
	Description *string            `json:"description"`
	ItemCount   int64              `json:"item_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAllLocations(ctx context.Context) ([]ListAllLocationsRow, error) {
	rows, err := q.db.Query(ctx, listAllLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllLocationsRow
	for rows.Next() {
		var i ListAllLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Description,
			&i.ItemCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationsByHome = `-- name: ListLocationsByHome :many
SELECT l.id, l.name, l.parent_id, l.description,
       COUNT(i.id) AS item_count, l.created_at, l.updated_at
FROM locations l
LEFT JOIN items i ON i.location_id = l.id
WHERE l.home_id = $1
GROUP BY l.id ORDER BY l.name
`

type ListLocationsByHomeRow struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	ParentID    *string            `json:"parent_id"`
	Description *string            `json:"description"`
	ItemCount   int64              `json:"item_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListLocationsByHome(ctx context.Context, homeID string) ([]ListLocationsByHomeRow, error) {
	rows, err := q.db.Query(ctx, listLocationsByHome, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationsByHomeRow
	for rows.Next() {
		var i ListLocationsByHomeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Description,
			&i.ItemCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :exec
UPDATE locations SET name = $2, parent_id = $3, description = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateLocationParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	ParentID    *string `json:"parent_id"`
	Description *string `json:"description"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) error {
	_, err := q.db.Exec(ctx, updateLocation,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.Description,
	)
	return err
}
