// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceMaintenanceSchedule = `-- name: AdvanceMaintenanceSchedule :exec
UPDATE maintenance_schedules
SET last_performed_at = COALESCE($2, CURRENT_DATE),
    next_due_at = COALESCE($2, CURRENT_DATE) + (frequency_value || ' ' || frequency_unit)::interval,
    updated_at = NOW()
WHERE id = $1
`

type AdvanceMaintenanceScheduleParams struct {
	ID              string     `json:"id"`
	LastPerformedAt *time.Time `json:"last_performed_at"`
}

func (q *Queries) AdvanceMaintenanceSchedule(ctx context.Context, arg AdvanceMaintenanceScheduleParams) error {
	_, err := q.db.Exec(ctx, advanceMaintenanceSchedule, arg.ID, arg.LastPerformedAt)
	return err
}

const createMaintenanceLog = `-- name: CreateMaintenanceLog :one
INSERT INTO maintenance_logs (item_id, title, notes, cost, performed_at, created_by, home_id, schedule_id)
VALUES ($1, $2, $3, $4, COALESCE($5, CURRENT_DATE), $6, $7, $8)
RETURNING id, item_id, NULL::text AS item_name, title, notes, cost, performed_at, created_at
`

type CreateMaintenanceLogParams struct {
	ItemID     *string        `json:"item_id"`
	Title      string         `json:"title"`
	Notes      *string        `json:"notes"`
	Cost       pgtype.Numeric `json:"cost"`
	Column5    interface{}    `json:"column_5"`
	CreatedBy  pgtype.Int8    `json:"created_by"`
	HomeID     *string        `json:"home_id"`
	ScheduleID *string        `json:"schedule_id"`
}

type CreateMaintenanceLogRow struct {
	ID          string             `json:"id"`
	ItemID      *string            `json:"item_id"`
	ItemName    *string            `json:"item_name"`
	Title       string             `json:"title"`
	Notes       *string            `json:"notes"`
	Cost        pgtype.Numeric     `json:"cost"`
	PerformedAt pgtype.Date        `json:"performed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateMaintenanceLog(ctx context.Context, arg CreateMaintenanceLogParams) (CreateMaintenanceLogRow, error) {
	row := q.db.QueryRow(ctx, createMaintenanceLog,
		arg.ItemID,
		arg.Title,
		arg.Notes,
		arg.Cost,
		arg.Column5,
		arg.CreatedBy,
		arg.HomeID,
		arg.ScheduleID,
	)
	var i CreateMaintenanceLogRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.ItemName,
		&i.Title,
		&i.Notes,
		&i.Cost,
		&i.PerformedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMaintenanceSchedule = `-- name: CreateMaintenanceSchedule :one
INSERT INTO maintenance_schedules (home_id, item_id, title, notes, frequency_value, frequency_unit, next_due_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7, CURRENT_DATE), $8)
RETURNING id, item_id, NULL::text AS item_name, title, notes, frequency_value, frequency_unit,
          last_performed_at, next_due_at, created_at, updated_at
`

type CreateMaintenanceScheduleParams struct {
	HomeID         string      `json:"home_id"`
	ItemID         *string     `json:"item_id"`
	Title          string      `json:"title"`
	Notes          *string     `json:"notes"`
	FrequencyValue int32       `json:"frequency_value"`
	FrequencyUnit  string      `json:"frequency_unit"`
	Column7        interface{} `json:"column_7"`
	CreatedBy      pgtype.Int8 `json:"created_by"`
}

type CreateMaintenanceScheduleRow struct {
	ID              string             `json:"id"`
	ItemID          *string            `json:"item_id"`
	ItemName        *string            `json:"item_name"`
	Title           string             `json:"title"`
	Notes           *string            `json:"notes"`
	FrequencyValue  int32              `json:"frequency_value"`
	FrequencyUnit   string             `json:"frequency_unit"`
	LastPerformedAt *time.Time         `json:"last_performed_at"`
	NextDueAt       pgtype.Date        `json:"next_due_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateMaintenanceSchedule(ctx context.Context, arg CreateMaintenanceScheduleParams) (CreateMaintenanceScheduleRow, error) {
	row := q.db.QueryRow(ctx, createMaintenanceSchedule,
		arg.HomeID,
		arg.ItemID,
		arg.Title,
		arg.Notes,
		arg.FrequencyValue,
		arg.FrequencyUnit,
		arg.Column7,
		arg.CreatedBy,
	)
	var i CreateMaintenanceScheduleRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.ItemName,
		&i.Title,
		&i.Notes,
		&i.FrequencyValue,
		&i.FrequencyUnit,
		&i.LastPerformedAt,
		&i.NextDueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMaintenanceLog = `-- name: DeleteMaintenanceLog :exec
DELETE FROM maintenance_logs WHERE id = $1
`

func (q *Queries) DeleteMaintenanceLog(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMaintenanceLog, id)
	return err
}

const deleteMaintenanceSchedule = `-- name: DeleteMaintenanceSchedule :exec
DELETE FROM maintenance_schedules WHERE id = $1
`

func (q *Queries) DeleteMaintenanceSchedule(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMaintenanceSchedule, id)
	return err
}

const listMaintenanceSchedules = `-- name: ListMaintenanceSchedules :many
SELECT ms.id, ms.item_id, i.name AS item_name, ms.title, ms.notes,
       ms.frequency_value, ms.frequency_unit,
       ms.last_performed_at, ms.next_due_at,
       ms.created_at, ms.updated_at
FROM maintenance_schedules ms
LEFT JOIN items i ON i.id = ms.item_id
WHERE ms.home_id = $1
ORDER BY ms.next_due_at ASC, ms.created_at ASC
`

type ListMaintenanceSchedulesRow struct {
	ID              string             `json:"id"`
	ItemID          *string            `json:"item_id"`
	ItemName        *string            `json:"item_name"`
	Title           string             `json:"title"`
	Notes           *string            `json:"notes"`
	FrequencyValue  int32              `json:"frequency_value"`
	FrequencyUnit   string             `json:"frequency_unit"`
	LastPerformedAt *time.Time         `json:"last_performed_at"`
	NextDueAt       pgtype.Date        `json:"next_due_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListMaintenanceSchedules(ctx context.Context, homeID string) ([]ListMaintenanceSchedulesRow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceSchedules, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaintenanceSchedulesRow
	for rows.Next() {
		var i ListMaintenanceSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.ItemName,
			&i.Title,
			&i.Notes,
			&i.FrequencyValue,
			&i.FrequencyUnit,
			&i.LastPerformedAt,
			&i.NextDueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaintenanceSchedule = `-- name: UpdateMaintenanceSchedule :one
UPDATE maintenance_schedules
SET item_id = $2, title = $3, notes = $4,
    frequency_value = $5, frequency_unit = $6,
    next_due_at = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, item_id, NULL::text AS item_name, title, notes, frequency_value, frequency_unit,
          last_performed_at, next_due_at, created_at, updated_at
`

type UpdateMaintenanceScheduleParams struct {
	ID             string      `json:"id"`
	ItemID         *string     `json:"item_id"`
	Title          string      `json:"title"`
	Notes          *string     `json:"notes"`
	FrequencyValue int32       `json:"frequency_value"`
	FrequencyUnit  string      `json:"frequency_unit"`
	NextDueAt      pgtype.Date `json:"next_due_at"`
}

type UpdateMaintenanceScheduleRow struct {
	ID              string             `json:"id"`
	ItemID          *string            `json:"item_id"`
	ItemName        *string            `json:"item_name"`
	Title           string             `json:"title"`
	Notes           *string            `json:"notes"`
	FrequencyValue  int32              `json:"frequency_value"`
	FrequencyUnit   string             `json:"frequency_unit"`
	LastPerformedAt *time.Time         `json:"last_performed_at"`
	NextDueAt       pgtype.Date        `json:"next_due_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateMaintenanceSchedule(ctx context.Context, arg UpdateMaintenanceScheduleParams) (UpdateMaintenanceScheduleRow, error) {
	row := q.db.QueryRow(ctx, updateMaintenanceSchedule,
		arg.ID,
		arg.ItemID,
		arg.Title,
		arg.Notes,
		arg.FrequencyValue,
		arg.FrequencyUnit,
		arg.NextDueAt,
	)
	var i UpdateMaintenanceScheduleRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.ItemName,
		&i.Title,
		&i.Notes,
		&i.FrequencyValue,
		&i.FrequencyUnit,
		&i.LastPerformedAt,
		&i.NextDueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
