// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ElectricalBreaker struct {
	ID              string             `json:"id"`
	PanelID         string             `json:"panel_id"`
	Slot            int32              `json:"slot"`
	Label           *string            `json:"label"`
	Amps            pgtype.Int4        `json:"amps"`
	BreakerType     string             `json:"breaker_type"`
	IsGfci          bool               `json:"is_gfci"`
	IsAfci          bool               `json:"is_afci"`
	Notes           *string            `json:"notes"`
	FloorPlanAreaID *string            `json:"floor_plan_area_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ElectricalPanel struct {
	ID             string             `json:"id"`
	HomeID         string             `json:"home_id"`
	Name           string             `json:"name"`
	TotalAmps      int32              `json:"total_amps"`
	TotalSlots     int32              `json:"total_slots"`
	LocationNote   *string            `json:"location_note"`
	ParentPanelID  *string            `json:"parent_panel_id"`
	FedByBreakerID *string            `json:"fed_by_breaker_id"`
	SortOrder      int32              `json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type FloorPlanArea struct {
	ID         string             `json:"id"`
	HomeID     string             `json:"home_id"`
	DocumentID *string            `json:"document_id"`
	Name       string             `json:"name"`
	Color      string             `json:"color"`
	Geometry   []byte             `json:"geometry"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type FloorPlanShape struct {
	ID         string             `json:"id"`
	HomeID     string             `json:"home_id"`
	DocumentID *string            `json:"document_id"`
	ItemID     *string            `json:"item_id"`
	Label      *string            `json:"label"`
	Color      string             `json:"color"`
	Geometry   []byte             `json:"geometry"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Home struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	AddressStreet  *string            `json:"address_street"`
	AddressCity    *string            `json:"address_city"`
	AddressState   *string            `json:"address_state"`
	AddressZip     *string            `json:"address_zip"`
	AddressCountry *string            `json:"address_country"`
	PropertyType   *string            `json:"property_type"`
	YearBuilt      pgtype.Int4        `json:"year_built"`
	Sqft           pgtype.Numeric     `json:"sqft"`
	Notes          *string            `json:"notes"`
	PurchasePrice  pgtype.Numeric     `json:"purchase_price"`
	PurchasedAt    *time.Time         `json:"purchased_at"`
	EstimatedValue pgtype.Numeric     `json:"estimated_value"`
	MortgageLender *string            `json:"mortgage_lender"`
	MortgageNotes  *string            `json:"mortgage_notes"`
	HoaName        *string            `json:"hoa_name"`
	HoaContact     *string            `json:"hoa_contact"`
	HoaMonthlyDues pgtype.Numeric     `json:"hoa_monthly_dues"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Acreage        pgtype.Numeric     `json:"acreage"`
}

type HomeDocument struct {
	ID           string             `json:"id"`
	HomeID       string             `json:"home_id"`
	Filename     string             `json:"filename"`
	ContentType  string             `json:"content_type"`
	FilePath     string             `json:"file_path"`
	Size         int64              `json:"size"`
	DocumentType *string            `json:"document_type"`
	FloorLevel   pgtype.Int4        `json:"floor_level"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type HomeMember struct {
	HomeID    string             `json:"home_id"`
	UserID    int64              `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type HomePhoto struct {
	ID            string             `json:"id"`
	HomeID        string             `json:"home_id"`
	Filename      string             `json:"filename"`
	ContentType   string             `json:"content_type"`
	FilePath      string             `json:"file_path"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ThumbnailPath *string            `json:"thumbnail_path"`
}

type Item struct {
	ID                string             `json:"id"`
	HomeID            string             `json:"home_id"`
	Name              string             `json:"name"`
	Description       *string            `json:"description"`
	LocationID        *string            `json:"location_id"`
	Status            string             `json:"status"`
	Manufacturer      *string            `json:"manufacturer"`
	Model             *string            `json:"model"`
	Serial            *string            `json:"serial"`
	PurchasePrice     pgtype.Numeric     `json:"purchase_price"`
	PurchasedAt       *time.Time         `json:"purchased_at"`
	Warranty          *string            `json:"warranty"`
	Insured           bool               `json:"insured"`
	Notes             *string            `json:"notes"`
	AssetID           *string            `json:"asset_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Tier              string             `json:"tier"`
	GridRow           pgtype.Int4        `json:"grid_row"`
	GridCol           pgtype.Int4        `json:"grid_col"`
	WarrantyExpiresAt *time.Time         `json:"warranty_expires_at"`
}

type ItemCustomField struct {
	ID        string             `json:"id"`
	ItemID    string             `json:"item_id"`
	FieldKey  string             `json:"field_key"`
	Label     string             `json:"label"`
	Value     *string            `json:"value"`
	ValueType string             `json:"value_type"`
	Unit      *string            `json:"unit"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ItemDocument struct {
	ID          string             `json:"id"`
	ItemID      string             `json:"item_id"`
	Filename    string             `json:"filename"`
	ContentType string             `json:"content_type"`
	FilePath    string             `json:"file_path"`
	Size        int64              `json:"size"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ItemLabel struct {
	ItemID  string `json:"item_id"`
	LabelID string `json:"label_id"`
}

type ItemPhoto struct {
	ID            string             `json:"id"`
	ItemID        string             `json:"item_id"`
	Filename      string             `json:"filename"`
	ContentType   string             `json:"content_type"`
	FilePath      string             `json:"file_path"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	IsCover       bool               `json:"is_cover"`
	ThumbnailPath *string            `json:"thumbnail_path"`
}

type Label struct {
	ID        string             `json:"id"`
	HomeID    string             `json:"home_id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Location struct {
	ID           string             `json:"id"`
	HomeID       string             `json:"home_id"`
	Name         string             `json:"name"`
	ParentID     *string            `json:"parent_id"`
	Description  *string            `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LocationType string             `json:"location_type"`
	GridRows     pgtype.Int4        `json:"grid_rows"`
	GridCols     pgtype.Int4        `json:"grid_cols"`
}

type LocationPaint struct {
	ID           string             `json:"id"`
	LocationID   string             `json:"location_id"`
	PaintColorID string             `json:"paint_color_id"`
	Surface      string             `json:"surface"`
	SurfaceNote  *string            `json:"surface_note"`
	PaintedOn    *time.Time         `json:"painted_on"`
	Coats        pgtype.Int4        `json:"coats"`
	Notes        *string            `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type MaintenanceLog struct {
	ID          string             `json:"id"`
	HomeID      *string            `json:"home_id"`
	ItemID      *string            `json:"item_id"`
	ScheduleID  *string            `json:"schedule_id"`
	Title       string             `json:"title"`
	Notes       *string            `json:"notes"`
	Cost        pgtype.Numeric     `json:"cost"`
	PerformedAt pgtype.Date        `json:"performed_at"`
	CreatedBy   pgtype.Int8        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MaintenanceSchedule struct {
	ID              string             `json:"id"`
	HomeID          string             `json:"home_id"`
	ItemID          *string            `json:"item_id"`
	Title           string             `json:"title"`
	Notes           *string            `json:"notes"`
	FrequencyValue  int32              `json:"frequency_value"`
	FrequencyUnit   string             `json:"frequency_unit"`
	LastPerformedAt *time.Time         `json:"last_performed_at"`
	NextDueAt       pgtype.Date        `json:"next_due_at"`
	CreatedBy       pgtype.Int8        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type PaintColor struct {
	ID        string             `json:"id"`
	HomeID    string             `json:"home_id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	Brand     *string            `json:"brand"`
	ColorCode *string            `json:"color_code"`
	Sheen     *string            `json:"sheen"`
	Notes     *string            `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt *time.Time         `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Reminder struct {
	ID           string             `json:"id"`
	UserID       int64              `json:"user_id"`
	Key          string             `json:"key"`
	Title        string             `json:"title"`
	Body         string             `json:"body"`
	Tone         string             `json:"tone"`
	DismissedAt  *time.Time         `json:"dismissed_at"`
	SnoozedUntil *time.Time         `json:"snoozed_until"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SystemSetting struct {
	Lock          bool `json:"lock"`
	SetupComplete bool `json:"setup_complete"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
