// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: paint_colors.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPaintColorUsage = `-- name: CountPaintColorUsage :one
SELECT COUNT(*) FROM location_paint WHERE paint_color_id = $1
`

func (q *Queries) CountPaintColorUsage(ctx context.Context, paintColorID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPaintColorUsage, paintColorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocationPaint = `-- name: CreateLocationPaint :one
INSERT INTO location_paint (location_id, paint_color_id, surface, surface_note, painted_on, coats, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateLocationPaintParams struct {
	LocationID   string      `json:"location_id"`
	PaintColorID string      `json:"paint_color_id"`
	Surface      string      `json:"surface"`
	SurfaceNote  *string     `json:"surface_note"`
	PaintedOn    *time.Time  `json:"painted_on"`
	Coats        pgtype.Int4 `json:"coats"`
	Notes        *string     `json:"notes"`
}

func (q *Queries) CreateLocationPaint(ctx context.Context, arg CreateLocationPaintParams) (string, error) {
	row := q.db.QueryRow(ctx, createLocationPaint,
		arg.LocationID,
		arg.PaintColorID,
		arg.Surface,
		arg.SurfaceNote,
		arg.PaintedOn,
		arg.Coats,
		arg.Notes,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createPaintColor = `-- name: CreatePaintColor :one
INSERT INTO paint_colors (home_id, name, color, brand, color_code, sheen, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, color, brand, color_code, sheen, notes, created_at, updated_at
`

type CreatePaintColorParams struct {
	HomeID    string  `json:"home_id"`
	Name      string  `json:"name"`
	Color     string  `json:"color"`
	Brand     *string `json:"brand"`
	ColorCode *string `json:"color_code"`
	Sheen     *string `json:"sheen"`
	Notes     *string `json:"notes"`
}

type CreatePaintColorRow struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	Brand     *string            `json:"brand"`
	ColorCode *string            `json:"color_code"`
	Sheen     *string            `json:"sheen"`
	Notes     *string            `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePaintColor(ctx context.Context, arg CreatePaintColorParams) (CreatePaintColorRow, error) {
	row := q.db.QueryRow(ctx, createPaintColor,
		arg.HomeID,
		arg.Name,
		arg.Color,
		arg.Brand,
		arg.ColorCode,
		arg.Sheen,
		arg.Notes,
	)
	var i CreatePaintColorRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Brand,
		&i.ColorCode,
		&i.Sheen,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLocationPaint = `-- name: DeleteLocationPaint :exec
DELETE FROM location_paint WHERE id = $1
`

func (q *Queries) DeleteLocationPaint(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLocationPaint, id)
	return err
}

const deletePaintColor = `-- name: DeletePaintColor :exec
DELETE FROM paint_colors WHERE id = $1
`

func (q *Queries) DeletePaintColor(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePaintColor, id)
	return err
}

const getLocationPaint = `-- name: GetLocationPaint :one
SELECT lp.id, lp.location_id, lp.paint_color_id, lp.surface, lp.surface_note,
       lp.painted_on, lp.coats, lp.notes, lp.created_at, lp.updated_at,
       pc.name AS paint_name, pc.color AS paint_color, pc.brand AS paint_brand,
       pc.color_code AS paint_color_code, pc.sheen AS paint_sheen
FROM location_paint lp
JOIN paint_colors pc ON pc.id = lp.paint_color_id
WHERE lp.id = $1
`

type GetLocationPaintRow struct {
	ID             string             `json:"id"`
	LocationID     string             `json:"location_id"`
	PaintColorID   string             `json:"paint_color_id"`
	Surface        string             `json:"surface"`
	SurfaceNote    *string            `json:"surface_note"`
	PaintedOn      *time.Time         `json:"painted_on"`
	Coats          pgtype.Int4        `json:"coats"`
	Notes          *string            `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PaintName      string             `json:"paint_name"`
	PaintColor     string             `json:"paint_color"`
	PaintBrand     *string            `json:"paint_brand"`
	PaintColorCode *string            `json:"paint_color_code"`
	PaintSheen     *string            `json:"paint_sheen"`
}

func (q *Queries) GetLocationPaint(ctx context.Context, id string) (GetLocationPaintRow, error) {
	row := q.db.QueryRow(ctx, getLocationPaint, id)
	var i GetLocationPaintRow
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.PaintColorID,
		&i.Surface,
		&i.SurfaceNote,
		&i.PaintedOn,
		&i.Coats,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaintName,
		&i.PaintColor,
		&i.PaintBrand,
		&i.PaintColorCode,
		&i.PaintSheen,
	)
	return i, err
}

const getPaintColor = `-- name: GetPaintColor :one
SELECT pc.id, pc.name, pc.color, pc.brand, pc.color_code, pc.sheen, pc.notes,
       COUNT(lp.id) AS location_count, pc.created_at, pc.updated_at
FROM paint_colors pc
LEFT JOIN location_paint lp ON lp.paint_color_id = pc.id
WHERE pc.id = $1
GROUP BY pc.id
`

type GetPaintColorRow struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Color         string             `json:"color"`
	Brand         *string            `json:"brand"`
	ColorCode     *string            `json:"color_code"`
	Sheen         *string            `json:"sheen"`
	Notes         *string            `json:"notes"`
	LocationCount int64              `json:"location_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPaintColor(ctx context.Context, id string) (GetPaintColorRow, error) {
	row := q.db.QueryRow(ctx, getPaintColor, id)
	var i GetPaintColorRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Brand,
		&i.ColorCode,
		&i.Sheen,
		&i.Notes,
		&i.LocationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPaintColors = `-- name: ListAllPaintColors :many
SELECT pc.id, pc.name, pc.color, pc.brand, pc.color_code, pc.sheen, pc.notes,
       COUNT(lp.id) AS location_count, pc.created_at, pc.updated_at
FROM paint_colors pc
LEFT JOIN location_paint lp ON lp.paint_color_id = pc.id
GROUP BY pc.id ORDER BY pc.name
`

type ListAllPaintColorsRow struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Color         string             `json:"color"`
	Brand         *string            `json:"brand"`
	ColorCode     *string            `json:"color_code"`
	Sheen         *string            `json:"sheen"`
	Notes         *string            `json:"notes"`
	LocationCount int64              `json:"location_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAllPaintColors(ctx context.Context) ([]ListAllPaintColorsRow, error) {
	rows, err := q.db.Query(ctx, listAllPaintColors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPaintColorsRow
	for rows.Next() {
		var i ListAllPaintColorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Brand,
			&i.ColorCode,
			&i.Sheen,
			&i.Notes,
			&i.LocationCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationPaint = `-- name: ListLocationPaint :many
SELECT lp.id, lp.location_id, lp.paint_color_id, lp.surface, lp.surface_note,
       lp.painted_on, lp.coats, lp.notes, lp.created_at, lp.updated_at,
       pc.name AS paint_name, pc.color AS paint_color, pc.brand AS paint_brand,
       pc.color_code AS paint_color_code, pc.sheen AS paint_sheen
FROM location_paint lp
JOIN paint_colors pc ON pc.id = lp.paint_color_id
WHERE lp.location_id = $1
ORDER BY lp.surface, lp.created_at
`

type ListLocationPaintRow struct {
	ID             string             `json:"id"`
	LocationID     string             `json:"location_id"`
	PaintColorID   string             `json:"paint_color_id"`
	Surface        string             `json:"surface"`
	SurfaceNote    *string            `json:"surface_note"`
	PaintedOn      *time.Time         `json:"painted_on"`
	Coats          pgtype.Int4        `json:"coats"`
	Notes          *string            `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PaintName      string             `json:"paint_name"`
	PaintColor     string             `json:"paint_color"`
	PaintBrand     *string            `json:"paint_brand"`
	PaintColorCode *string            `json:"paint_color_code"`
	PaintSheen     *string            `json:"paint_sheen"`
}

func (q *Queries) ListLocationPaint(ctx context.Context, locationID string) ([]ListLocationPaintRow, error) {
	rows, err := q.db.Query(ctx, listLocationPaint, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationPaintRow
	for rows.Next() {
		var i ListLocationPaintRow
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.PaintColorID,
			&i.Surface,
			&i.SurfaceNote,
			&i.PaintedOn,
			&i.Coats,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaintName,
			&i.PaintColor,
			&i.PaintBrand,
			&i.PaintColorCode,
			&i.PaintSheen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaintColorsByHome = `-- name: ListPaintColorsByHome :many
SELECT pc.id, pc.name, pc.color, pc.brand, pc.color_code, pc.sheen, pc.notes,
       COUNT(lp.id) AS location_count, pc.created_at, pc.updated_at
FROM paint_colors pc
LEFT JOIN location_paint lp ON lp.paint_color_id = pc.id
WHERE pc.home_id = $1
GROUP BY pc.id ORDER BY pc.name
`

type ListPaintColorsByHomeRow struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Color         string             `json:"color"`
	Brand         *string            `json:"brand"`
	ColorCode     *string            `json:"color_code"`
	Sheen         *string            `json:"sheen"`
	Notes         *string            `json:"notes"`
	LocationCount int64              `json:"location_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPaintColorsByHome(ctx context.Context, homeID string) ([]ListPaintColorsByHomeRow, error) {
	rows, err := q.db.Query(ctx, listPaintColorsByHome, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaintColorsByHomeRow
	for rows.Next() {
		var i ListPaintColorsByHomeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Brand,
			&i.ColorCode,
			&i.Sheen,
			&i.Notes,
			&i.LocationCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationHomeID = `-- name: LocationHomeID :one
SELECT home_id FROM locations WHERE id = $1
`

func (q *Queries) LocationHomeID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, locationHomeID, id)
	var home_id string
	err := row.Scan(&home_id)
	return home_id, err
}

const paintColorHomeID = `-- name: PaintColorHomeID :one
SELECT home_id FROM paint_colors WHERE id = $1
`

func (q *Queries) PaintColorHomeID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, paintColorHomeID, id)
	var home_id string
	err := row.Scan(&home_id)
	return home_id, err
}

const updateLocationPaint = `-- name: UpdateLocationPaint :exec
UPDATE location_paint SET paint_color_id = $2, surface = $3, surface_note = $4,
       painted_on = $5, coats = $6, notes = $7, updated_at = NOW()
WHERE id = $1
`

type UpdateLocationPaintParams struct {
	ID           string      `json:"id"`
	PaintColorID string      `json:"paint_color_id"`
	Surface      string      `json:"surface"`
	SurfaceNote  *string     `json:"surface_note"`
	PaintedOn    *time.Time  `json:"painted_on"`
	Coats        pgtype.Int4 `json:"coats"`
	Notes        *string     `json:"notes"`
}

func (q *Queries) UpdateLocationPaint(ctx context.Context, arg UpdateLocationPaintParams) error {
	_, err := q.db.Exec(ctx, updateLocationPaint,
		arg.ID,
		arg.PaintColorID,
		arg.Surface,
		arg.SurfaceNote,
		arg.PaintedOn,
		arg.Coats,
		arg.Notes,
	)
	return err
}

const updatePaintColor = `-- name: UpdatePaintColor :exec
UPDATE paint_colors SET name = $2, color = $3, brand = $4, color_code = $5,
       sheen = $6, notes = $7, updated_at = NOW()
WHERE id = $1
`

type UpdatePaintColorParams struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Color     string  `json:"color"`
	Brand     *string `json:"brand"`
	ColorCode *string `json:"color_code"`
	Sheen     *string `json:"sheen"`
	Notes     *string `json:"notes"`
}

func (q *Queries) UpdatePaintColor(ctx context.Context, arg UpdatePaintColorParams) error {
	_, err := q.db.Exec(ctx, updatePaintColor,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Brand,
		arg.ColorCode,
		arg.Sheen,
		arg.Notes,
	)
	return err
}
