// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package store

import (
	"context"
)

const createItemPhoto = `-- name: CreateItemPhoto :one
INSERT INTO item_photos (item_id, filename, content_type, file_path)
VALUES ($1, $2, $3, 'pending')
RETURNING id, item_id, filename, content_type, file_path, created_at
`

type CreateItemPhotoParams struct {
	ItemID      string `json:"item_id"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
}

func (q *Queries) CreateItemPhoto(ctx context.Context, arg CreateItemPhotoParams) (ItemPhoto, error) {
	row := q.db.QueryRow(ctx, createItemPhoto, arg.ItemID, arg.Filename, arg.ContentType)
	var i ItemPhoto
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Filename,
		&i.ContentType,
		&i.FilePath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteItemPhoto = `-- name: DeleteItemPhoto :exec
DELETE FROM item_photos WHERE id = $1
`

func (q *Queries) DeleteItemPhoto(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteItemPhoto, id)
	return err
}

const getItemPhotoFilePath = `-- name: GetItemPhotoFilePath :one
SELECT file_path FROM item_photos WHERE id = $1 AND item_id = $2
`

type GetItemPhotoFilePathParams struct {
	ID     string `json:"id"`
	ItemID string `json:"item_id"`
}

func (q *Queries) GetItemPhotoFilePath(ctx context.Context, arg GetItemPhotoFilePathParams) (string, error) {
	row := q.db.QueryRow(ctx, getItemPhotoFilePath, arg.ID, arg.ItemID)
	var file_path string
	err := row.Scan(&file_path)
	return file_path, err
}

const listItemPhotos = `-- name: ListItemPhotos :many
SELECT id, item_id, filename, content_type, file_path, created_at
FROM item_photos WHERE item_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListItemPhotos(ctx context.Context, itemID string) ([]ItemPhoto, error) {
	rows, err := q.db.Query(ctx, listItemPhotos, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemPhoto
	for rows.Next() {
		var i ItemPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Filename,
			&i.ContentType,
			&i.FilePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemPhotoPath = `-- name: UpdateItemPhotoPath :exec
UPDATE item_photos SET file_path = $1 WHERE id = $2
`

type UpdateItemPhotoPathParams struct {
	FilePath string `json:"file_path"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateItemPhotoPath(ctx context.Context, arg UpdateItemPhotoPathParams) error {
	_, err := q.db.Exec(ctx, updateItemPhotoPath, arg.FilePath, arg.ID)
	return err
}
