// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	AdvanceMaintenanceSchedule(ctx context.Context, arg AdvanceMaintenanceScheduleParams) error
	CompleteSetup(ctx context.Context) error
	CountAllItems(ctx context.Context) (int64, error)
	CountAllLabels(ctx context.Context) (int64, error)
	CountAllLocations(ctx context.Context) (int64, error)
	CountBreakerAtSlot(ctx context.Context, arg CountBreakerAtSlotParams) (int64, error)
	CountBreakersAtDoublePoleSlots(ctx context.Context, arg CountBreakersAtDoublePoleSlotsParams) (int64, error)
	CountHomeOwners(ctx context.Context, homeID string) (int64, error)
	CountItemsByHome(ctx context.Context, homeID string) (int64, error)
	CountLabelsByHome(ctx context.Context, homeID string) (int64, error)
	CountLocationChildren(ctx context.Context, parentID *string) (int64, error)
	CountLocationsByHome(ctx context.Context, homeID string) (int64, error)
	CountSubpanels(ctx context.Context, parentPanelID *string) (int64, error)
	CreateBreaker(ctx context.Context, arg CreateBreakerParams) (ElectricalBreaker, error)
	CreateFirstHome(ctx context.Context, name string) (string, error)
	CreateFloorPlanArea(ctx context.Context, arg CreateFloorPlanAreaParams) (FloorPlanArea, error)
	CreateFloorPlanShape(ctx context.Context, arg CreateFloorPlanShapeParams) (FloorPlanShape, error)
	CreateHome(ctx context.Context, arg CreateHomeParams) (string, error)
	CreateHomeDocument(ctx context.Context, arg CreateHomeDocumentParams) (CreateHomeDocumentRow, error)
	CreateHomePhoto(ctx context.Context, arg CreateHomePhotoParams) (HomePhoto, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (string, error)
	CreateItemDocument(ctx context.Context, arg CreateItemDocumentParams) (ItemDocument, error)
	CreateItemPhoto(ctx context.Context, arg CreateItemPhotoParams) (ItemPhoto, error)
	CreateLabel(ctx context.Context, arg CreateLabelParams) (CreateLabelRow, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (CreateLocationRow, error)
	CreateMaintenanceLog(ctx context.Context, arg CreateMaintenanceLogParams) (CreateMaintenanceLogRow, error)
	CreateMaintenanceSchedule(ctx context.Context, arg CreateMaintenanceScheduleParams) (CreateMaintenanceScheduleRow, error)
	CreatePanel(ctx context.Context, arg CreatePanelParams) (ElectricalPanel, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBreaker(ctx context.Context, id string) error
	DeleteFloorPlanArea(ctx context.Context, id string) error
	DeleteFloorPlanShape(ctx context.Context, id string) error
	DeleteHome(ctx context.Context, id string) error
	DeleteHomeDocument(ctx context.Context, id string) error
	DeleteHomeMember(ctx context.Context, arg DeleteHomeMemberParams) error
	DeleteHomePhoto(ctx context.Context, id string) error
	DeleteItem(ctx context.Context, id string) error
	DeleteItemDocument(ctx context.Context, id string) error
	DeleteItemLabels(ctx context.Context, itemID string) error
	DeleteItemPhoto(ctx context.Context, id string) error
	DeleteLabel(ctx context.Context, id string) error
	DeleteLocation(ctx context.Context, id string) error
	DeleteMaintenanceLog(ctx context.Context, id string) error
	DeleteMaintenanceSchedule(ctx context.Context, id string) error
	DeletePanel(ctx context.Context, id string) error
	DeleteReminderByKey(ctx context.Context, key string) error
	DeleteUser(ctx context.Context, id int64) error
	DismissReminder(ctx context.Context, arg DismissReminderParams) (int64, error)
	GetBreaker(ctx context.Context, id string) (ElectricalBreaker, error)
	GetBreakerPanelID(ctx context.Context, id string) (string, error)
	GetFloorPlanAreaHomeID(ctx context.Context, id string) (string, error)
	GetFloorPlanShape(ctx context.Context, id string) (FloorPlanShape, error)
	GetFloorPlanShapeHomeID(ctx context.Context, id string) (string, error)
	GetHomeDocumentFilePath(ctx context.Context, arg GetHomeDocumentFilePathParams) (string, error)
	GetHomeForUser(ctx context.Context, arg GetHomeForUserParams) (GetHomeForUserRow, error)
	GetHomeMemberRole(ctx context.Context, arg GetHomeMemberRoleParams) (string, error)
	GetHomePhotoFilePath(ctx context.Context, arg GetHomePhotoFilePathParams) (string, error)
	GetItemDocumentFilePath(ctx context.Context, arg GetItemDocumentFilePathParams) (string, error)
	GetItemPhotoFilePath(ctx context.Context, arg GetItemPhotoFilePathParams) (string, error)
	GetLabel(ctx context.Context, id string) (GetLabelRow, error)
	GetLocation(ctx context.Context, id string) (GetLocationRow, error)
	GetMaxGridCell(ctx context.Context, locationID *string) (GetMaxGridCellRow, error)
	GetPanel(ctx context.Context, id string) (ElectricalPanel, error)
	GetPanelHomeID(ctx context.Context, id string) (string, error)
	GetSystemStatus(ctx context.Context) (bool, error)
	GetSystemStatusForUpdate(ctx context.Context) (bool, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserIDByEmail(ctx context.Context, email string) (int64, error)
	InsertItemLabel(ctx context.Context, arg InsertItemLabelParams) error
	ListAllLabels(ctx context.Context) ([]ListAllLabelsRow, error)
	ListAllLocations(ctx context.Context) ([]ListAllLocationsRow, error)
	ListBreakers(ctx context.Context, panelID string) ([]ElectricalBreaker, error)
	ListFloorPlanAreas(ctx context.Context, homeID string) ([]FloorPlanArea, error)
	ListFloorPlanShapes(ctx context.Context, homeID string) ([]FloorPlanShape, error)
	ListHomeDocuments(ctx context.Context, homeID string) ([]HomeDocument, error)
	ListHomeMembers(ctx context.Context, homeID string) ([]ListHomeMembersRow, error)
	ListHomePhotos(ctx context.Context, homeID string) ([]HomePhoto, error)
	ListHomesForUser(ctx context.Context, userID int64) ([]ListHomesForUserRow, error)
	ListItemDocuments(ctx context.Context, itemID string) ([]ItemDocument, error)
	ListItemPhotos(ctx context.Context, itemID string) ([]ItemPhoto, error)
	ListLabelsByHome(ctx context.Context, homeID string) ([]ListLabelsByHomeRow, error)
	ListLocationsByHome(ctx context.Context, homeID string) ([]ListLocationsByHomeRow, error)
	ListMaintenanceSchedules(ctx context.Context, homeID string) ([]ListMaintenanceSchedulesRow, error)
	ListPanels(ctx context.Context, homeID string) ([]ElectricalPanel, error)
	ListReminders(ctx context.Context, userID int64) ([]ListRemindersRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	SnoozeReminder(ctx context.Context, arg SnoozeReminderParams) (int64, error)
	UpdateBreaker(ctx context.Context, arg UpdateBreakerParams) (ElectricalBreaker, error)
	UpdateFloorPlanArea(ctx context.Context, arg UpdateFloorPlanAreaParams) (FloorPlanArea, error)
	UpdateFloorPlanShape(ctx context.Context, arg UpdateFloorPlanShapeParams) (FloorPlanShape, error)
	UpdateHome(ctx context.Context, arg UpdateHomeParams) error
	UpdateHomeDocumentFloorLevel(ctx context.Context, arg UpdateHomeDocumentFloorLevelParams) error
	UpdateHomeDocumentPath(ctx context.Context, arg UpdateHomeDocumentPathParams) error
	UpdateHomeDocumentType(ctx context.Context, arg UpdateHomeDocumentTypeParams) error
	UpdateHomePhotoPath(ctx context.Context, arg UpdateHomePhotoPathParams) error
	UpdateItem(ctx context.Context, arg UpdateItemParams) error
	UpdateItemDocumentPath(ctx context.Context, arg UpdateItemDocumentPathParams) error
	UpdateItemPhotoPath(ctx context.Context, arg UpdateItemPhotoPathParams) error
	UpdateLabel(ctx context.Context, arg UpdateLabelParams) error
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) error
	UpdateMaintenanceSchedule(ctx context.Context, arg UpdateMaintenanceScheduleParams) (UpdateMaintenanceScheduleRow, error)
	UpdatePanel(ctx context.Context, arg UpdatePanelParams) (ElectricalPanel, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpsertHomeMember(ctx context.Context, arg UpsertHomeMemberParams) error
	UpsertReminder(ctx context.Context, arg UpsertReminderParams) error
}

var _ Querier = (*Queries)(nil)
