// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteReminderByKey = `-- name: DeleteReminderByKey :exec
DELETE FROM reminders WHERE key = $1
`

func (q *Queries) DeleteReminderByKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteReminderByKey, key)
	return err
}

const dismissReminder = `-- name: DismissReminder :execrows
UPDATE reminders SET dismissed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type DismissReminderParams struct {
	ID     string `json:"id"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) DismissReminder(ctx context.Context, arg DismissReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, dismissReminder, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listReminders = `-- name: ListReminders :many
SELECT id, key, title, body, tone, snoozed_until, created_at
FROM reminders
WHERE user_id = $1
  AND dismissed_at IS NULL
  AND (snoozed_until IS NULL OR snoozed_until <= NOW())
ORDER BY created_at ASC
`

type ListRemindersRow struct {
	ID           string             `json:"id"`
	Key          string             `json:"key"`
	Title        string             `json:"title"`
	Body         string             `json:"body"`
	Tone         string             `json:"tone"`
	SnoozedUntil *time.Time         `json:"snoozed_until"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListReminders(ctx context.Context, userID int64) ([]ListRemindersRow, error) {
	rows, err := q.db.Query(ctx, listReminders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRemindersRow
	for rows.Next() {
		var i ListRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Title,
			&i.Body,
			&i.Tone,
			&i.SnoozedUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snoozeReminder = `-- name: SnoozeReminder :execrows
UPDATE reminders SET snoozed_until = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type SnoozeReminderParams struct {
	ID           string     `json:"id"`
	UserID       int64      `json:"user_id"`
	SnoozedUntil *time.Time `json:"snoozed_until"`
}

func (q *Queries) SnoozeReminder(ctx context.Context, arg SnoozeReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, snoozeReminder, arg.ID, arg.UserID, arg.SnoozedUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertReminder = `-- name: UpsertReminder :exec
INSERT INTO reminders (user_id, key, title, body, tone)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, key) DO UPDATE
SET title = EXCLUDED.title, body = EXCLUDED.body, tone = EXCLUDED.tone,
    dismissed_at = NULL, snoozed_until = NULL, updated_at = NOW()
`

type UpsertReminderParams struct {
	UserID int64  `json:"user_id"`
	Key    string `json:"key"`
	Title  string `json:"title"`
	Body   string `json:"body"`
	Tone   string `json:"tone"`
}

func (q *Queries) UpsertReminder(ctx context.Context, arg UpsertReminderParams) error {
	_, err := q.db.Exec(ctx, upsertReminder,
		arg.UserID,
		arg.Key,
		arg.Title,
		arg.Body,
		arg.Tone,
	)
	return err
}
