// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_settings.sql

package store

import (
	"context"
)

const completeSetup = `-- name: CompleteSetup :exec
UPDATE system_settings SET setup_complete = TRUE
`

func (q *Queries) CompleteSetup(ctx context.Context) error {
	_, err := q.db.Exec(ctx, completeSetup)
	return err
}

const getSystemStatus = `-- name: GetSystemStatus :one
SELECT setup_complete FROM system_settings LIMIT 1
`

func (q *Queries) GetSystemStatus(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, getSystemStatus)
	var setup_complete bool
	err := row.Scan(&setup_complete)
	return setup_complete, err
}

const getSystemStatusForUpdate = `-- name: GetSystemStatusForUpdate :one
SELECT setup_complete FROM system_settings LIMIT 1 FOR UPDATE
`

func (q *Queries) GetSystemStatusForUpdate(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, getSystemStatusForUpdate)
	var setup_complete bool
	err := row.Scan(&setup_complete)
	return setup_complete, err
}
